<html>
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=UTF8">
	<title>Карта Ануира</title>
</head>
<body>

<h1>Карта Ануира.</h1>
Города обзначены чёрным цветом. Дороги между городами обозначены красным. 
Незначительные детали обозначены белым цветом.
Если найден кратчайший путь между двумя городами, он на карте обозначается синими стрелками.

<?php
if($logger)
	$logger -> info("image file : " . $path . "/map.png");
$pathReal = realpath("../data");	
if($logger)
	$logger -> info("pathReal : " . $pathReal);
?>	

<img src="<?php echo $path . '/map.png'; ?>" width="100%" height="95%" alt="Error: <?php echo $path . '/map.png'; ?>">
</body>
</html>
