<html>
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=UTF8">
	<title>Путеводитель тест</title>
</head>
<body>
ZF вид PHP скрипт пользователя earthundead, работающий с Bash <br>

<?php
	echo "<br> Демонстрируем output = `man update-grub`";

	$output = `man update-grub`;

	print "<pre>$output</pre>";
	$ProgramDir=getcwd();
	echo "ProgramDir=$ProgramDir";
	
	$applicationFilesPath = $this->filesPath;
	if($applicationFilesPath)
		include_once $applicationFilesPath . "/model/euFunctions.php";

?>


</body>
</html>
