<html>
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=UTF8">
	<title>Показ Логфайла</title>
</head>
<body>

<?php

	function PrintDescription($dataFilesPath)
		{ 
		$Succses=file_exists($dataFilesPath . "/Описание.txt");
		if($Succses)
			{
			$file=fopen($dataFilesPath . "/Описание.txt","r");
			while (!feof($file)) 
			    {
			    $string = fgets($file);
			    echo "$string <br>";
			    }
			}
		$Succses=fclose($file);
		}

	function Show($dataFilesPath)
		{
		$logfile=$dataFilesPath . "/logfile.log";
		echo("This prog logfile = $logfile <br>");
		$Succses=file_exists($logfile);
		echo("Вывод логфайла. Успех открытия : $Succses.<br>");
		if($Succses)
			{
			echo("Логфайл: <br>");
			$file=fopen($logfile,"r");
			while (!feof($file)) 
			    {
			    $string = fgets($file);
			    echo "$string <br>";
			    }
			}
		$Succses=fclose($file);
		echo("Вывод логфайла. Успех закрытия : $Succses.<br>");
		echo("Производится попытка стереть логфайл.<br>");
		$file=fopen($logfile,"w");
		if($file);
			echo("Логфайл стёрт.<br>");
		fclose($file);
		}

$dataFilesPath = $this->path;
PrintDescription($dataFilesPath);
Show($dataFilesPath);
?>

</body>
</html>
